# Generated by Django 5.0.1 on 2024-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
