# Generated by Django 5.0.1 on 2024-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customuser_date_added_customuser_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='star',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
