# Generated by Django 5.0.1 on 2024-03-04 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_mytrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrips',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, null=True, size=None),
        ),
    ]
