# Generated by Django 5.0.1 on 2024-03-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mytrips_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrips',
            name='images',
        ),
    ]
